elasticsearch:
  host: XXX
  api_key: XXX
  ssl: true
  verification_mode: none
  bulk:
    queue_max_size: 4096
    queue_max_mem_size: 1024
    display_every: 100
    chunk_size: 125
    max_concurrency: 4
    chunk_max_mem_size: 50
    concurrent_downloads: 40
  request_timeout: 120
  max_wait_duration: 120
  initial_backoff_duration: 1
  backoff_multiplier: 2
  log_level: info

connector_id: "V0-6UocBeNy9m6iDazts"
service_type: 'sharepoint'

service:
  idling: 30
  heartbeat: 300
  max_errors: 20
  max_errors_span: 600
  max_concurrent_syncs: 1
  job_cleanup_interval: 300
  log_level: INFO

native_service_types:
  - mongodb
  - mysql
  - network_drive
  - s3
  - google_cloud_storage
  - azure_blob_storage
  - postgresql
  - oracle
  - dir
  - sharepoint
  - mssql
  - jira
# Connector client settings
#connector_id: 'changeme'
#service_type: 'changeme'
sources:
  mongodb: connectors.sources.mongo:MongoDataSource
  s3: connectors.sources.s3:S3DataSource
  dir: connectors.sources.directory:DirectoryDataSource
  mysql: connectors.sources.mysql:MySqlDataSource
  network_drive: connectors.sources.network_drive:NASDataSource
  google_cloud_storage: connectors.sources.google_cloud_storage:GoogleCloudStorageDataSource
  azure_blob_storage: connectors.sources.azure_blob_storage:AzureBlobStorageDataSource
  postgresql: connectors.sources.postgresql:PostgreSQLDataSource
  oracle: connectors.sources.oracle:OracleDataSource
  sharepoint: connectors.sources.sharepoint:SharepointDataSource
  mssql: connectors.sources.mssql:MSSQLDataSource
  jira: connectors.sources.jira:JiraDataSource
